name: Reusable Java CI Workflow
description: Runs Java tests and processes coverage reports.

on:
  workflow_call:

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Grant Execute Permission for Gradle
      shell: bash
      run: |
        if [ -f ./gradlew ]; then
          chmod +x gradlew
        else
          echo "gradlew not found!"
          exit 1
        fi

    - name: Run Tests and Generate Coverage Report
      shell: bash
      run: ./gradlew test jacocoTestReport

    - name: List Directory Contents
      shell: bash
      run: ls -R

    - name: Run Coverage Script
      uses: actions/github-script@v7
      with:
        script: |
          const script = require('${{ github.action_path }}/script/script.js'); 
          console.log(script({ github, context }));
